#!/usr/bin/env python3

##
## EPITECH PROJECT, 2023
## B-YEP-400-PAR-4-1-zappy-viktor.bruggeman
## File description:
## zappy_ai
##

# @file zappy_ai

from ai import main
import sys
import signal

## @author Damien
## @brief Ctrl-c handler so, when doing it, ther is no error messages
def signal_handler(sig, frame):
    exit(0)

signal.signal(signal.SIGINT, signal_handler)

## @author Pierre-Louis
## @brief Removes useless executable name in argv
## @return arcv without executable name
def remove_executable_name() -> int:
    return sys.argv[1:]

## @author Damien and Pierre-Louis
## @brief Calls the main of the main.py file
## @param argc is the length of argv
## @param argv contain argument given by the user
## @details Checks if the file is executed as a main program
while 1:
    if __name__ == "__main__":
        main.main(len(sys.argv) - 1, remove_executable_name())
        pass
