#!/usr/bin/env python3

##
## EPITECH PROJECT, 2023
## B-YEP-400-PAR-4-1-zappy-viktor.bruggeman
## File description:
## zappy_ai
##

from AI import main
import sys

argv = sys.argv
argc = len(argv)
exit(main.main(argc, argv))
