##
## EPITECH PROJECT, 2023
## B-YEP-400-PAR-4-1-zappy-viktor.bruggeman
## File description:
## .github/workflows/git_action.yml
##

# @file git_action.yml

## @author Pierre-Louis LEROY
## @brief Ce github action permet pour l'instant exit sucess à chaque push sur la branche main
name: git_action

on:
  push:
    branches: [main]

jobs:
  git_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: exit 0
        run: |
          exit 0

################## Git action for check Coding Style in C ##################
#      - name: Launch .sh
#        run: ./.github/coding-style.sh . .
#
#          if [[ -s coding-style-reports.log ]]
#          then
#            echo "Coding Style dans le report.log"
#            exit 1
#          else
#            echo "Aucune Coding Style dans le report.log"
#            exit 0
#          fi
###########################################################################
